gText_HowMayIServeYou:: @ 8272A21
	.string "Welcome!\p"
	.string "How may I serve you?$"

gText_PleaseComeAgain:: @ 8272A3F
	.string "Please come again!$"

gText_PlayerWhatCanIDoForYou:: @ 8272A52
	.string "{PLAYER}{STRING 5}, welcome!\p"
	.string "What can I do for you?$"

gText_LeafHowCanIHelp:: @ 800023
	.string "LEAF: Hey there assistant!\n"
	.string "What would you like this time?$"

gText_LeafGoodLuckOutThere:: @ 800025
	.string "Good luck out there!$"
